AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TableName:
    Type: String
    Default: 'Darren-SampleTable'
    Description: (Required) The name of the new DynamoDB table you want to create and save
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z]+$
Resources:
  Type: AWS::DynamoDB::Table
  Properties: {
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
    }
